name: CListery's Readme

on:
  schedule:
    - cron: '10 22 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "zh"
          SECTION_NAME: "waka_time"
          COMMIT_MESSAGE: "Updated with Dev Metrics"
          COMMIT_BY_ME: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_TIMEZONE: "Asia/Shanghai"
          SHOW_LINES_OF_CODE: "True"
          UPDATED_DATE_FORMAT: "%Y-%m-%d %H:%M:%S"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "False"
          SHOW_PROJECTS: "True"
          SHOW_LOC_CHART: "TRUE"
          SYMBOL_VERSION: "2"
      - uses: Platane/snk/svg-only@v3
        with:
          # github user name to read the contribution graph from (**required**)
          # using action context var `github.repository_owner` or specified user
          github_user_name: ${{ github.repository_owner }}

          # list of files to generate.
          # one file per line. Each output can be customized with options as query string.
          #
          #  supported options:
          #  - palette:     A preset of color, one of [github, github-dark, github-light]
          #  - color_snake: Color of the snake
          #  - color_dots:  Coma separated list of dots color.
          #                 The first one is 0 contribution, then it goes from the low contribution to the highest.
          #                 Exactly 5 colors are expected.
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      - name: push github-contribution-grid-snake.svg to the snake-gen branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: snake-gen
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
